// ------------------------------------------------
// ------------------------------------------------
// ------------------------------------------------

export const itemsHorizontal = [
  {src:"/images/medias/h/frappadingue-1.jpg",
  alt:"Image 1",
  },
  {src:"/images/medias/h/frappadingue-2.jpg",
  alt:"Image 1",
  },
  {src:"/images/medias/h/frappadingue-3.jpg",
  alt:"Image 1",
  },
  {src:"/images/medias/h/frappadingue-4.jpg",
  alt:"Image 1",
  },
  {src:"/images/medias/h/frappadingue-5.jpg",
  alt:"Image 1",
  },
  {src:"/images/medias/h/frappadingue-6.jpg",
  alt:"Image 1",
  },
  {src:"/images/medias/h/frappadingue-7.jpg",
  alt:"Image 1",
  },
  {src:"/images/medias/h/frappadingue-8.jpg",
  alt:"Image 1",
  },
  {src:"/images/medias/h/frappadingue-9.jpg",
  alt:"Image 1",
  },
  {src:"/images/medias/h/frappadingue-10.jpg",
  alt:"Image 1",
  },
  {src:"/images/medias/h/frappadingue-11.jpg",
  alt:"Image 1",
  },
  {src:"/images/medias/h/frappadingue-12.jpg",
  alt:"Image 1",
  },
  {src:"/images/medias/h/frappadingue-13.jpg",
  alt:"Image 1",
  },
  {src:"/images/medias/h/frappadingue-14.jpg",
  alt:"Image 1",
  },
  {src:"/images/medias/h/frappadingue-15.jpg",
  alt:"Image 1",
  },
  {src:"/images/medias/h/frappadingue-16.jpg",
  alt:"Image 1",
  },
  {src:"/images/medias/h/frappadingue-17.jpg",
  alt:"Image 1",
  },
  {src:"/images/medias/h/frappadingue-18.jpg",
  alt:"Image 1",
  },
  {src:"/images/medias/h/frappadingue-19.jpg",
  alt:"Image 1",
  },
  {src:"/images/medias/h/frappadingue-20.jpg",
  alt:"Image 1",
  },
  {src:"/images/medias/h/frappadingue-21.jpg",
  alt:"Image 1",
  },
  {src:"/images/medias/h/frappadingue-22.jpg",
  alt:"Image 1",
  },
  {src:"/images/medias/h/frappadingue-23.jpg",
  alt:"Image 1",
  },
  {src:"/images/medias/h/frappadingue-24.jpg",
  alt:"Image 1",
  },
  {src:"/images/medias/h/frappadingue-25.jpg",
  alt:"Image 1",
  },
  {src:"/images/medias/h/frappadingue-26.jpg",
  alt:"Image 1",
  },
  {src:"/images/medias/h/frappadingue-27.jpg",
  alt:"Image 1",
  },
  {src:"/images/medias/h/frappadingue-28.jpg",
  alt:"Image 1",
  },
  {src:"/images/medias/h/frappadingue-29.jpg",
  alt:"Image 1",
  },
  {src:"/images/medias/h/frappadingue-30.jpg",
  alt:"Image 1",
  },
  {src:"/images/medias/h/frappadingue-31.jpg",
  alt:"Image 1",
  },
  {src:"/images/medias/h/frappadingue-32.jpg",
  alt:"Image 1",
  },
  {src:"/images/medias/h/frappadingue-33.jpg",
  alt:"Image 1",
  },
  {src:"/images/medias/h/frappadingue-34.jpg",
  alt:"Image 1",
  },
  {src:"/images/medias/h/frappadingue-35.jpg",
  alt:"Image 1",
  },
  {src:"/images/medias/h/frappadingue-36.jpg",
  alt:"Image 1",
  },
  {src:"/images/medias/h/frappadingue-37.jpg",
  alt:"Image 1",
  },
  {src:"/images/medias/h/frappadingue-38.jpg",
  alt:"Image 1",
  },
  {src:"/images/medias/h/frappadingue-39.jpg",
  alt:"Image 1",
  },
  {src:"/images/medias/h/frappadingue-40.jpg",
  alt:"Image 1",
  },
  {src:"/images/medias/h/frappadingue-41.jpg",
  alt:"Image 1",
  },
  {src:"/images/medias/h/frappadingue-42.jpg",
  alt:"Image 1",
  },
  {src:"/images/medias/h/frappadingue-43.jpg",
  alt:"Image 1",
  },
  {src:"/images/medias/h/frappadingue-44.jpg",
  alt:"Image 1",
  },
  {src:"/images/medias/h/frappadingue-45.jpg",
  alt:"Image 1",
  },
  {src:"/images/medias/h/frappadingue-46.jpg",
  alt:"Image 1",
  },
  {src:"/images/medias/h/frappadingue-47.jpg",
  alt:"Image 1",
  },
  {src:"/images/medias/h/frappadingue-48.jpg",
  alt:"Image 1",
  },
  {src:"/images/medias/h/frappadingue-49.jpg",
  alt:"Image 1",
  },
  {src:"/images/medias/h/frappadingue-50.jpg",
  alt:"Image 1",
  },
  {src:"/images/medias/h/frappadingue-51.jpg",
  alt:"Image 1",
  },
  {src:"/images/medias/h/frappadingue-52.jpg",
  alt:"Image 1",
  },
  {src:"/images/medias/h/frappadingue-53.jpg",
  alt:"Image 1",
  },
  {src:"/images/medias/h/frappadingue-54.jpg",
  alt:"Image 1",
  },
  {src:"/images/medias/h/frappadingue-55.jpg",
  alt:"Image 1",
  },
  {src:"/images/medias/h/frappadingue-56.jpg",
  alt:"Image 1",
  },
  {src:"/images/medias/h/frappadingue-57.jpg",
  alt:"Image 1",
  },
  {src:"/images/medias/h/frappadingue-58.jpg",
  alt:"Image 1",
  },
  {src:"/images/medias/h/frappadingue-59.jpg",
  alt:"Image 1",
  },
  {src:"/images/medias/h/frappadingue-60.jpg",
  alt:"Image 1",
  },
  {src:"/images/medias/h/frappadingue-61.jpg",
  alt:"Image 1",
  },
  {src:"/images/medias/h/frappadingue-62.jpg",
  alt:"Image 1",
  },
]

// ------------------------------------------------
// ------------------------------------------------
// ------------------------------------------------

export const itemsVertical = [
  {src:"/images/medias/h/course-obstacle-frappadingue-1.jpg",
  alt:"Image 1",
  },
  {src:"/images/medias/h/course-obstacle-frappadingue-2.jpg",
  alt:"Image 1",
  },
  {src:"/images/medias/h/course-obstacle-frappadingue-3.jpg",
  alt:"Image 1",
  },
  {src:"/images/medias/h/course-obstacle-frappadingue-4.jpg",
  alt:"Image 1",
  },
  {src:"/images/medias/h/course-obstacle-frappadingue-5.jpg",
  alt:"Image 1",
  },
  {src:"/images/medias/h/course-obstacle-frappadingue-6.jpg",
  alt:"Image 1",
  },
  {src:"/images/medias/h/course-obstacle-frappadingue-7.jpg",
  alt:"Image 1",
  },
  {src:"/images/medias/h/course-obstacle-frappadingue-8.jpg",
  alt:"Image 1",
  },
  {src:"/images/medias/h/course-obstacle-frappadingue-9.jpg",
  alt:"Image 1",
  },
  {src:"/images/medias/h/course-obstacle-frappadingue-10.jpg",
  alt:"Image 1",
  },
  {src:"/images/medias/h/course-obstacle-frappadingue-11.jpg",
  alt:"Image 1",
  },
  {src:"/images/medias/h/course-obstacle-frappadingue-12.jpg",
  alt:"Image 1",
  },
]

